# Generated by Django 5.0.3 on 2024-03-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceattendence', '0002_standard_studentuser_standard_subject_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceattendence.standard'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceattendence.standard'),
        ),
    ]
