# Generated by Django 5.0.3 on 2024-03-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceattendence', '0003_alter_studentuser_standard_alter_subject_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='latitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='longitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
